### ISSUE TITLE
Windows 10 Anniversary Edition Resetting FlipFlopWheel

### ISSUE THREAD

**Issue by fdncred** [jamie-pate/flipflop-windows-wheel#6]
I'm not sure if it's Outlook or Edge or what but something in Windows is continually resetting the FlipFlopWheel value.  Any ideas how to prevent this?

I have to run your app several times a day. Perhaps if there were a tray application that just monitored that key and reset it on change.

Thanks,
Darren

**Comment by jamie-pate** [comment]
Maybe you could determine the culprit via http://www.nirsoft.net/utils/reg_file_from_application.html and file a bug with them. Probably the best time to reset the value would be once, directly before a reboot since the devices seem to only read it during initialization anyways.

**Comment by jamie-pate** [comment]
Going to attempt to figure out what's going on by follwing the directions here https://blogs.msdn.microsoft.com/cobold/2011/11/29/monitoring-when-registry-keys-are-modified/ to 'audit' the registry key.

**Comment by fdncred** [comment]
Not glad to hear you're having the same problem but glad to hear I'm not the only one. I've tried several things to figure out what is updating the key but I haven't figured it out yet.

**Comment by jamie-pate** [comment]
So far it's only happened the once. Are you continuing to have troubles? Have you identified any particular actor causing it?
Hopefully it's been fixed by a followup update to w10 anniversary edition.

**Comment by fdncred** [comment]
I have it from time to time. It's unpredictable so far. I think it's a windows app that is reversing it like Edge or Store, but I haven't confirmed it. The problem with the programs I was using to monitor the change is that they tell you when it has been changed but not what is changing it.

**Comment by jamie-pate** [comment]
I suggest using the audit method I mentioned above. This uses the windows event logger and does show the name of the process that changes. You can test it with FlipFlopWheel, once you enable the audit it should generate an event in the windows event log whenever you update a setting.

**Comment by fdncred** [comment]
I couldn't get auditpol to register changes when I used FlipFlowWheel. This is the command line I used as Admin:
auditpol /set /subcategory:”Registry” /success:enable

**Comment by fdncred** [comment]
I'm seeing stranger behavior.  One windows explorer will be respecting the value in the registry and another Windows Explorer will be doing the opposite.  If I run FlipWheel, it fixes it. I still have the registry monitor updating my EventViewer but there are no events that I can track down to changing that key.  I don't get it.  Perhaps it's a bug in Explorer?
